- name: 'blocky: validate config & restart blocky.service'
  ansible.builtin.command: '/usr/local/sbin/blocky validate --config /etc/blocky/config.yml'
  notify:
    - 'blocky: restart blocky.service'

- name: 'blocky: restart blocky.service'
  ansible.builtin.service:
    name: 'blocky.service'
    state: 'restarted'
