apps__apps__dependent_var: []
apps__apps__group_var: []
apps__apps__host_var: []
apps__apps__role_var: []
apps__apps__combined_var: '{{ apps__apps__role_var +
  apps__apps__group_var +
  apps__apps__host_var +
  apps__apps__dependent_var
 }}'
