kvm_host__libvirt_guests_on_shutdown: 'shutdown'
kvm_host__libvirt_guests_parallel_shutdown: 5
kvm_host__libvirt_guests_service_enabled: true
kvm_host__libvirt_guests_shutdown_timeout: 300
kvm_host__libvirtd_service_enabled: true
kvm_host__networks: []
kvm_host__pools: []

# -----------------------------------------------------------------------------

kvm_host__python__dependent_modules:
  - 'python3-libvirt'
  - 'python3-lxml'
