wordpress__database_host: 'localhost'
wordpress__database_name: 'wordpress'
wordpress__disallow_file_edit: true
wordpress__install_dir: '/var/www/html/{{ wordpress__url }}'
wordpress__plugins: []
wordpress__version: 'latest'


# -----------------------------------------------------------------------------

wordpress__apache_httpd__mods__dependent_var:
  - filename: 'proxy_fcgi'
    enabled: true
    state: 'present'
wordpress__apache_httpd__vhosts__dependent_var:
  - conf_server_name: '{{ wordpress__url }}'
    by_role: 'wordpress'
    enabled: true
    filename: 'wordpress'
    state: 'present'
    template: 'wordpress'
    allowed_http_methods:
      - 'GET'
      - 'OPTIONS'
      - 'POST'
    authz_file_extensions: |-
        Require all granted
    authz_document_root: |-
        Require all granted
    virtualhost_port: 80
    conf_allow_override: 'All'
    conf_directory_index: 'index.php'
    conf_document_root: '{{ wordpress__install_dir }}'
    conf_options: 'FollowSymLinks'
    conf_timeout: 30
    raw: !unsafe |-
      <Files wp-config.php>
          Require all denied
      </Files>
      <Files xmlrpc.php>
          Require all denied
      </Files>

wordpress__mariadb_server__databases__dependent_var:
  - name: '{{ wordpress__database_name }}'
    collation: 'utf8_general_ci'
    encoding: 'utf8'
    state: 'present'
wordpress__mariadb_server__users__dependent_var:
  - username: '{{ wordpress__database_user["username"] }}'
    password: '{{ wordpress__database_user["password"] }}'
    host: '{{ wordpress__database_host }}'
    priv:
      - '{{ wordpress__database_name }}.*:CREATE,ALTER,SELECT,INSERT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE'
    state: 'present'

wordpress__php__modules__dependent_var:
  - name: 'php-gd'
    state: 'present'
  - name: 'php-imagick'
    state: 'present'
  - name: 'php-intl'
    state: 'present'
  - name: 'php-mysql'
    state: 'present'
  - name: 'php-zip'
    state: 'present'

wordpress__selinux__booleans__dependent_var:
  - key: 'httpd_can_network_connect'
    value: 'on'
