- block:

  - name: 'Set platform/version specific variables'
    ansible.builtin.import_role:
      name: 'shared'
      tasks_from: 'platform-variables.yml'

  - name: 'Install package {{ yum_utils__package }}'
    ansible.builtin.package:
      name: '{{ yum_utils__package }}'
      state: 'present'

  tags:
    - 'yum_utils'
