- block:

  - name: 'Set platform/version specific variables'
    ansible.builtin.import_role:
      name: 'shared'
      tasks_from: 'platform-variables.yml'

  - name: 'Make sure SELinux {{ policycoreutils__package }} are installed'
    ansible.builtin.package:
      name: '{{ policycoreutils__package }}'
      state: 'present'

  tags:
    - 'policycoreutils'
