mariadb_server__cnf_character_set_server__role_var: 'utf8mb4'
mariadb_server__cnf_collation_server__role_var: 'utf8mb4_unicode_ci'
mariadb_server__cnf_expire_logs_days__role_var: 0.000000
mariadb_server__cnf_innodb_buffer_pool_size__role_var: '128M'
mariadb_server__cnf_innodb_file_per_table__role_var: 'ON'
mariadb_server__cnf_innodb_flush_log_at_trx_commit__role_var: 1
mariadb_server__cnf_innodb_io_capacity__role_var: 200
mariadb_server__cnf_innodb_log_file_size__role_var: '96M'
mariadb_server__cnf_interactive_timeout__role_var: 28800
mariadb_server__cnf_join_buffer_size__role_var: '256K'
mariadb_server__cnf_log_error__role_var: '/var/log/mariadb/mariadb.log'
mariadb_server__cnf_lower_case_table_names__role_var: 0
mariadb_server__cnf_max_allowed_packet__role_var: '16M'
mariadb_server__cnf_max_connections__role_var: 64
mariadb_server__cnf_max_heap_table_size__role_var: '16M'
mariadb_server__cnf_performance_schema__role_var: 'ON'
mariadb_server__cnf_query_cache_limit__role_var: '1M'
mariadb_server__cnf_query_cache_size__role_var: 0
mariadb_server__cnf_query_cache_type__role_var: 'OFF'
mariadb_server__cnf_skip_name_resolve__role_var: 'ON'
mariadb_server__cnf_slow_query_log__role_var: 0
mariadb_server__cnf_slow_query_log_file__role_var: '/var/log/mariadb/mariadb-slowquery.log'
mariadb_server__cnf_table_definition_cache__role_var: 400
mariadb_server__cnf_tmp_table_size__role_var: '16M'
mariadb_server__cnf_wait_timeout__role_var: 28800
