ansible_init__ansible_collections: []
ansible_init__ansinv_path: '{{ inventory_dir }}/../'
ansible_init__inventories: []
ansible_init__lfops_url: 'https://github.com/Linuxfabrik/lfops.git'
ansible_init__roles: []
ansible_init__version: 'main'
