- block:

  - name: 'Update ansible_init (ansinv) itself'
    ansible.builtin.git:
      repo: '{{ ansible_init__url }}'
      dest: '{{ ansible_init__ansinv_path }}'
      version: '{{ ansible_init__version }}'
    ignore_errors: true

  - name: 'Update ../lfops'
    ansible.builtin.git:
      repo: 'git@github.com:Linuxfabrik/lfops.git'
      dest: '{{ ansible_init__ansinv_path }}../lfops'
      version: 'main'
    ignore_errors: true

  tags:
    - 'ansible_init'


- block:

  - name: 'Load repo list'
    ansible.builtin.include_vars:
      file: '{{ ansible_init__ansinv_path }}/control_node/group_vars/repos.yml'

  tags:
    - 'ansible_init'
    - 'ansible_init:command'


- block:

  - name: 'Clone the inventories'
    ansible.builtin.git:
      repo: '{{ item["url"] }}'
      dest: '{{ ansible_init__ansinv_path }}/{{ item["name"] }}'
      version: '{{ item["version"] }}'
    loop: '{{ ansible_init__inventories }}'
    ignore_errors: true

  - name: 'Install ansible collections'
    community.general.ansible_galaxy_install:
      name: '{{ item["name"] }}'
      # no_deps: '{{ item["no_deps"] | d("False") }}'
      type: '{{ item["type"] | d("collection") }}'
      force: true # from the doc: *Ansible 2.9 and 2.10*: Must be `true' to upgrade roles and collections.
    loop: "{{ ansible_init__ansible_collections }}"
    ignore_errors: true

  tags:
    - 'ansible_init'
