icingaweb2_module_monitoring__api_host: 'localhost'
icingaweb2_module_monitoring__api_port: 5665
icingaweb2_module_monitoring__api_user_login: '{{ icingaweb2__api_user_login }}'
icingaweb2_module_monitoring__backend_database_name: '{{ icinga2_master__database_name }}'

# -----------------------------------------------------------------------------

icingaweb2_module_monitoring__icingaweb2__resources__dependent_var:
  - name: '{{ icingaweb2_module_monitoring__backend_database_name }}'
    type: 'db'
    db: 'mysql'
    host: '{{ icinga2_master__database_host }}'
    port: 3306
    dbname: '{{ icingaweb2_module_monitoring__backend_database_name }}'
    username: '{{ icinga2_master__database_login.username }}'
    password: '{{ icinga2_master__database_login.password }}'
    charset: '' # required to be blank for special characters (eg umlaute) to be displayed correctly
