# escape all backslashes for tty terminals
motd__logo_tty: |+
  powered by
  .____    .__                       _____      ___.         .__ __
  |    |   |__| ____  __ _____  ____/ ____\\____ \\_ |_________|__|  | __
  |    |   |  |/    \\|  |  \\  \\/  /\\   __\\\\__  \\ | __ \\_  __ \\  |  |/ /
  |    |___|  |   |  \\  |  />    <  |  |   / __ \\| \\_\\ \\  | \\/  |    <
  |_______ \\__|___|  /____//__/\\_ \\ |__|  (____  /___  /__|  |__|__|_ \\
          \\/       \\/            \\/            \\/    \\/              \\/

# for ssh and other pseudo-terminals
motd__logo_pty: |+
  powered by
  .____    .__                       _____      ___.         .__ __
  |    |   |__| ____  __ _____  ____/ ____\____ \_ |_________|__|  | __
  |    |   |  |/    \|  |  \  \/  /\   __\\__  \ | __ \_  __ \  |  |/ /
  |    |___|  |   |  \  |  />    <  |  |   / __ \| \_\ \  | \/  |    <
  |_______ \__|___|  /____//__/\_ \ |__|  (____  /___  /__|  |__|__|_ \
          \/       \/            \/            \/    \/              \/

# CIS:
# Warning messages inform users who are attempting to login to the system of their legal
# status regarding the system and must include the name of the organization that owns the
# system and any monitoring policies that are in place.
motd__legal_notice: |+
  ************************************************************************
  *                                                                      *
  * This system is for the use of authorized users only. Individuals     *
  * using this computer system without authority or in excess of their   *
  * authority are subject to having all their activities on this system  *
  * monitored and recorded by system personnel. Anyone using this        *
  * system expressly consents to such monitoring and is advised that     *
  * if such monitoring reveals possible evidence of criminal activity    *
  * system personal may provide the evidence of such monitoring to law   *
  * enforcement officials.                                               *
  *                                                                      *
  ************************************************************************
