- block:

  - name: 'install collabora and dependent packages'
    ansible.builtin.package:
      name:
        - '{{ collabora__use_code | bool | ternary("CODE-brand", "collabora-online-brand") }}'
        - 'collaboraofficebasis-calc'
        - 'collaboraofficebasis-core'
        - 'collaboraofficebasis-draw'
        - 'collaboraofficebasis-extension-pdf-import'
        - 'collaboraofficebasis-graphicfilter'
        - 'collaboraofficebasis-images'
        - 'collaboraofficebasis-impress'
        - 'collaboraofficebasis-math'
        - 'collaboraofficebasis-ooofonts'
        - 'collaboraofficebasis-ooolinguistic'
        - 'collaboraofficebasis-python-script-provider'
        - 'collaboraofficebasis-pyuno'
        - 'collaboraofficebasis-writer'
        - 'coolwsd'
      state: 'present'

  - name: 'touch /var/log/coolwsd.log & chmod 0660 /var/log/coolwsd.log'
    ansible.builtin.file:
      path: '/var/log/coolwsd.log'
      state: 'touch'
      owner: 'cool'
      group: 'cool'
      mode: 0o640

  - name: 'Get the list of installed packages'
    ansible.builtin.package_facts:  # yamllint disable-line rule:empty-values
    check_mode: false # run task even if `--check` is specified

  - name: 'Get installed Collabora version'
    ansible.builtin.set_fact:
      collabora__installed_version: '{{ ansible_facts["packages"]["coolwsd"][0]["version"] | regex_search("\d+\.\d+\.\d+") }}'

  - name: 'deploy /etc/coolwsd/coolwsd.xml'
    ansible.builtin.template:
      src: 'etc/coolwsd/{{ collabora__installed_version }}-coolwsd{{ collabora__use_code | bool | ternary("-code", "") }}.xml.j2'
      dest: '/etc/coolwsd/coolwsd.xml'
      owner: 'cool'
      group: 'cool'
      mode: 0o640
    notify: 'collabora: restart coolwsd'

  - name: 'Remove rpmnew / rpmsave (and Debian equivalents)'
    ansible.builtin.include_role:
      name: 'shared'
      tasks_from: 'remove-rpmnew-rpmsave.yml'
    vars:
      shared__remove_rpmnew_rpmsave_config_file: '/etc/coolwsd/coolwsd.xml'

  - name: 'Deploy /etc/logrotate.d/coolwsd'
    ansible.builtin.template:
      src: 'etc/logrotate.d/coolwsd.j2'
      dest: '/etc/logrotate.d/coolwsd'
      owner: 'root'
      group: 'root'
      mode: 0o644

  - name: 'chown -R cool:cool /etc/coolwsd'
    ansible.builtin.command: 'chown -R cool:cool /etc/coolwsd'

  tags:
    - 'collabora'


- block:

  - name: 'install spell checker'
    ansible.builtin.package:
      name:
        - 'hunspell'
        - 'mythes'
      state: 'present'

  - name: 'Combined Language Packages:'
    ansible.builtin.debug:
      var: 'collabora__language_packages__combined_var'

  - name: 'install language packages'
    ansible.builtin.package:
      name: '{{ (collabora__language_packages__combined_var  | selectattr("state", "defined") | selectattr("state", "ne", "absent") | map(attribute="name"))
          + (collabora__language_packages__combined_var  | selectattr("state", "undefined") | map(attribute="name")) }}'
      state: 'present'

  - name: 'remove language packages'
    ansible.builtin.package:
      name: '{{ collabora__language_packages__combined_var  | selectattr("state", "defined") | selectattr("state", "eq", "absent") | map(attribute="name") }}'
      state: 'absent'

  tags:
    - 'collabora'
    - 'collabora:spell_check'


- block:

  - name: 'systemctl {{ collabora__service_enabled | bool | ternary("enable", "disable") }} --now coolwsd.service'
    ansible.builtin.systemd:
      name: 'coolwsd.service'
      enabled: '{{ collabora__service_enabled }}'
      state: '{{ collabora__service_enabled | bool | ternary("started", "stopped") }}'

  tags:
    - 'collabora'
    - 'collabora:state'
