icingaweb2_module_x509__database_host: 'localhost'
icingaweb2_module_x509__database_name: 'x509'

# -----------------------------------------------------------------------------

icingaweb2_module_x509__icingaweb2__resources__dependent_var:
  - name: '{{ icingaweb2_module_x509__database_name }}'
    type: 'db'
    db: 'mysql'
    host: '{{ icingaweb2_module_x509__database_host }}'
    port: 3306
    dbname: '{{ icingaweb2_module_x509__database_name }}'
    username: '{{ icingaweb2_module_x509__database_login["username"] }}'
    password: '{{ icingaweb2_module_x509__database_login["password"] }}'
    charset: 'utf8mb4'

icingaweb2_module_x509__mariadb_server__databases__dependent_var:
  - name: '{{ icingaweb2_module_x509__database_name }}'
    collation: 'utf8_general_ci'
    encoding: 'utf8'
    state: 'present'

icingaweb2_module_x509__mariadb_server__users__dependent_var:
  - username: '{{ icingaweb2_module_x509__database_login["username"] }}'
    password: '{{ icingaweb2_module_x509__database_login["password"] }}'
    host: '{{ icingaweb2_module_x509__database_host }}'
    priv:
      - '{{ icingaweb2_module_x509__database_name }}.*:CREATE,SELECT,INSERT,UPDATE,DELETE,DROP,ALTER,CREATE VIEW,INDEX,EXECUTE'
    state: 'present'

icingaweb2_module_x509__php__modules__dependent_var:
  - name: 'php-gmp'
    state: 'present'
  - name: 'php-openssl'
    state: 'present'
  - name: 'php-pcntl'
    state: 'present'
