# You probably want to perform platform specific tasks once, for the most specific match. In that
# case, use lookup('first_found') with the file list in order of most specific to least specific:

- name: 'Perform platform/version specific tasks'
  include_tasks: '{{ lookup("first_found", __task_file) }}'
  vars:
    __task_file:
      files:
        - '{{ ansible_facts["distribution"] }}_{{ ansible_facts["distribution_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}_{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}_{{ ansible_facts["distribution_version"] }}.yml'
        - '{{ ansible_facts["os_family"] }}_{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
        - 'os-not-supported.yml'
      paths:
        - '{{ role_path }}/tasks'
