repo_epel__gpg_key_dest: '/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-10'
repo_epel__gpg_key_url: 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-10'
repo_epel__repo_files:
  - 'RedHat10/etc/yum.repos.d/epel-testing.repo'
  - 'RedHat10/etc/yum.repos.d/epel.repo'
