stig__aide_calendar: '"*-*-* 05:{{ 59 | random(start=0, seed=inventory_hostname) }}:00"'

# Just for Apache httpd:
#   The OWASP ModSecurity Core Rules Set (CRS) is a set of open source web application
#   defensive rules for the ModSecurity web application firewall (WAF).
stig__apache_owasp_crs_main_version: 3  # default: 3 | value range: 2, 3
stig__apache_owasp_crs_rule_dir: '/etc/httpd/conf.d/crs'  # default: /etc/httpd/conf.d/crs

stig__audit_backlog_limit: 8192
stig__auditd_max_log_file: 8

stig__chrony_service_enabled: true
stig__ntp_service_enabled: false

# one of "LEGACY", "DEFAULT", "FUTURE" and "FIPS"
# FUTURE is harder than FIPS, but then some Repos like EPEL might not work any more
stig__crypto_policy: 'DEFAULT'

stig__gdm_login_banner_text: >
  -- WARNING --
  This system is for the use of authorized users only. Individuals
  using this computer system without authority or in excess of their
  authority are subject to having all their activities on this system
  monitored and recorded by system personnel. Anyone using this
  system expressly consents to such monitoring and is advised that
  if such monitoring reveals possible evidence of criminal activity
  system personal may provide the evidence of such monitoring to law
  enforcement officials.

# You must define a bootloader password at the host level, or the role will break. Use a password
# without special characters to avoid problems with the keyboard layout when working on the console.
# stig__grub2_password: 'ChoosePasswordWithoutSpecialChars'

# default:
# stig__ntp_pools:
#   - ch.pool.ntp.org
#   - ntp.metas.ch
# prefer "stig__ntp_pools" ("pool" directive in ntp.conf) over "stig__ntp_servers" ("server" directive).
# instead of "pool" in ntp.conf
stig__ntp_pools:
  - 'ch.pool.ntp.org'
  - 'ntp.metas.ch'

stig__pass_max_days: 60
stig__pass_min_days: 7
stig__pass_warn_age: 7

stig__pwquality_minlen: 14
stig__pwquality_minclass: 4

stig__remote_syslog:
  port: '514'
  proto: 'tcp'
  server: 'localhost'

stig__selinux_state: 'enforcing'
stig__selinux_type: 'targeted'

stig__shell_timeout: 900

stig__sshd_ciphers: 'chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
stig__sshd_clientalivecountmax: 0
stig__sshd_clientaliveinterval: 900
stig__sshd_kexalgorithms: 'curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256'
stig__sshd_logingracetime: 60
stig__sshd_loglevel: 'VERBOSE'
stig__sshd_macs: 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256'
stig__sshd_maxauthtries: 4
stig__sshd_maxsessions: 2

stig__sudo_logfile: '/var/log/sudo.log'

stig__uid_min: 1000

stig__umask: '027'

stig__user_inactivelock_days: 30
