fangfrisch_timer_enabled: true

# -----------------------------------------------------------------------------

fangfrisch__python_venv__venvs__dependent_var:
  - name: 'clamav-fangfrisch'
    packages:
      - 'fangfrisch'
    exposed_binaries:
      - 'fangfrisch'
    package_requirements:
      - 'python39'
      - 'python39-devel'
    python_executable: 'python3.9'
