repo_remi__repo_files:
  - 'RedHat7/etc/yum.repos.d/remi.repo'
  - 'RedHat7/etc/yum.repos.d/remi-glpi91.repo'
  - 'RedHat7/etc/yum.repos.d/remi-glpi92.repo'
  - 'RedHat7/etc/yum.repos.d/remi-glpi93.repo'
  - 'RedHat7/etc/yum.repos.d/remi-glpi94.repo'
  - 'RedHat7/etc/yum.repos.d/remi-modular.repo'
  - 'RedHat7/etc/yum.repos.d/remi-php54.repo'
  - 'RedHat7/etc/yum.repos.d/remi-php70.repo'
  - 'RedHat7/etc/yum.repos.d/remi-php71.repo'
  - 'RedHat7/etc/yum.repos.d/remi-php72.repo'
  - 'RedHat7/etc/yum.repos.d/remi-php73.repo'
  - 'RedHat7/etc/yum.repos.d/remi-php74.repo'
  - 'RedHat7/etc/yum.repos.d/remi-safe.repo'
