python__version: 3.9

# -----------------------------------------------------------------------------

python__modules__dependent_var: []
python__modules__group_var: []
python__modules__host_var: []
python__modules__role_var: []

python__modules__combined_var: '{{ python__modules__role_var +
  python__modules__group_var +
  python__modules__host_var +
  python__modules__dependent_var
  | flatten
 }}'
