- name: 'systemd_journald: restart systemd-journald'
  ansible.builtin.systemd:
    name: 'systemd-journald'
    state: 'restarted'
  when:
    - 'systemd_journald__service_state_result is not changed'
