- ansible.builtin.debug:
    msg:
      - 'journald-storage-configure.yml'

- ansible.builtin.lineinfile:
    path: '/etc/systemd/journald.conf'
    regexp: '"^#?Storage="'
    line: 'Storage=persistent'
    state: 'present'
