- ansible.builtin.debug:
    msg:
      - 'ssh-host-key-private-chmod.yml'

- ansible.builtin.command: '"{{ item }}"'
  become: true
  changed_when: false
  loop:
    - "find /etc/ssh -xdev -type f -name 'ssh_host_*_key' -exec chown root:root {} \\;"
    - "find /etc/ssh -xdev -type f -name 'ssh_host_*_key' -exec chmod 0600 {} \\;"
