- ansible.builtin.debug:
    msg:
      - 'sshd-ciphers-configure.yml'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^#?Ciphers'
    line: '"Ciphers {{ stig__sshd_ciphers }}"'
    state: 'present'
    validate: '/usr/sbin/sshd -t -f %s'
  when:
    - 'stig__sshd_ciphers is defined'
    - 'stig__sshd_ciphers != ""'
