- ansible.builtin.debug:
    msg:
      - 'sshd-kexalgorithms-configure.yml'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^#?KexAlgorithms'
    line: '"KexAlgorithms {{ stig__sshd_kexalgorithms }}"'
    state: 'present'
    validate: '/usr/sbin/sshd -t -f %s'
  when:
    - 'stig__sshd_kexalgorithms is defined'
    - 'stig__sshd_kexalgorithms != ""'
