- ansible.builtin.debug:
    msg:
      - 'umask-configure.yml'

- ansible.builtin.replace:
    path: '"{{ item }}"'
    regexp: '^\s*umask.*'
    replace: 'umask {{ stig__umask }}'
  loop:
    - '/etc/bashrc'
    - '/etc/csh.cshrc'
    - '/etc/profile'

- ansible.builtin.find:
    paths: '/etc/profile.d'
    patterns: '*.sh'
  register: 'files_matched'

- ansible.builtin.replace:
    path: '"{{ item }}"'
    regexp: '^\s*umask.*'
    replace: 'umask {{ stig__umask }}'
  loop: '"{{ files_matched.files | map(attribute="path") | list }}"'
