- ansible.builtin.debug:
    msg:
      - 'usermod-root-lock_uid_ge_0-configure.yml'

- ansible.builtin.shell: "cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {exit i}'"
  register: 'shell_output'
  changed_when: false
  check_mode: false

- ansible.builtin.command: 'passwd -l {{ item }}'
  changed_when: false
  failed_when: false
  loop: '"{{ shell_output.stdout_lines }}"'
  when:
    - 'shell_output.rc'
