- ansible.builtin.debug:
    msg:
      - 'usermod-all-lock_empty_passwords-configure.yml'

- ansible.builtin.shell: "cat /etc/shadow | awk -F: '($2 == \"\" ) {j++;print $1; } END {exit j}'"
  register: 'shell_output'
  changed_when: false
  check_mode: false

- ansible.builtin.command: 'passwd -l {{ item }}'
  changed_when: false
  failed_when: false
  loop: '"{{ shell_output.stdout_lines }}"'
  when:
    - 'shell_output.rc'
