- import_playbook: 'acme_sh.yml'
- import_playbook: 'ansible_init.yml'
- import_playbook: 'apache_httpd.yml'
- import_playbook: 'apache_solr.yml'
- import_playbook: 'apache_tomcat.yml'
- import_playbook: 'apps.yml'
- import_playbook: 'at.yml'
- import_playbook: 'audit.yml'
- import_playbook: 'bind.yml'
- import_playbook: 'chrony.yml'
- import_playbook: 'clamav.yml'
- import_playbook: 'cloud_init.yml'
- import_playbook: 'cockpit.yml'
- import_playbook: 'collabora.yml'
- import_playbook: 'coturn.yml'
- import_playbook: 'crypto_policy.yml'
- import_playbook: 'dnf_makecache.yml'
- import_playbook: 'dnf_versionlock.yml'
- import_playbook: 'docker.yml'
- import_playbook: 'duplicity.yml'
- import_playbook: 'elasticsearch_oss.yml'
- import_playbook: 'exoscale_vm.yml'
- import_playbook: 'fail2ban.yml'
- import_playbook: 'fangfrisch.yml'
- import_playbook: 'ffmpeg.yml'
- import_playbook: 'firewall.yml'
- import_playbook: 'freeipa_client.yml'
- import_playbook: 'freeipa_server.yml'
- import_playbook: 'gitlab_ce.yml'
- import_playbook: 'glances.yml'
- import_playbook: 'grafana.yml'
- import_playbook: 'grafana_grizzly.yml'
- import_playbook: 'haveged.yml'
- import_playbook: 'hetzner_vm.yml'
- import_playbook: 'hostname.yml'
- import_playbook: 'icinga2_agent.yml'
- import_playbook: 'icingaweb2.yml'
- import_playbook: 'icingaweb2_module_businessprocess.yml'
- import_playbook: 'icingaweb2_module_company.yml'
- import_playbook: 'icingaweb2_module_director.yml'
- import_playbook: 'icingaweb2_module_doc.yml'
- import_playbook: 'icingaweb2_module_incubator.yml'
- import_playbook: 'icingaweb2_module_monitoring.yml'
- import_playbook: 'influxdb.yml'
- import_playbook: 'infomaniak_vm.yml'
- import_playbook: 'kdump.yml'
- import_playbook: 'keepalived.yml'
- import_playbook: 'kernel_settings.yml'
- import_playbook: 'kvm_host.yml'
- import_playbook: 'kvm_vm.yml'
- import_playbook: 'libmaxminddb.yml'
- import_playbook: 'libreoffice.yml'
- import_playbook: 'login.yml'
- import_playbook: 'logrotate.yml'
- import_playbook: 'mailto_root.yml'
- import_playbook: 'mailx.yml'
- import_playbook: 'mariadb_server.yml'
- import_playbook: 'maxmind_geoip.yml'
- import_playbook: 'mcm_vm.yml'
- import_playbook: 'minio_client.yml'
- import_playbook: 'mod_maxminddb.yml'
- import_playbook: 'mongodb.yml'
- import_playbook: 'monitoring_plugins.yml'
- import_playbook: 'monitoring_plugins_grafana_dashboards.yml'
- import_playbook: 'motd.yml'
- import_playbook: 'network.yml'
- import_playbook: 'nfs_client.yml'
- import_playbook: 'nfs_server.yml'
- import_playbook: 'nodejs.yml'
- import_playbook: 'objectstore_backup.yml'
- import_playbook: 'open_vm_tools.yml'
- import_playbook: 'opensearch.yml'
- import_playbook: 'openvpn_server.yml'
- import_playbook: 'perl.yml'
- import_playbook: 'php.yml'
- import_playbook: 'policycoreutils.yml'
- import_playbook: 'postfix.yml'
- import_playbook: 'postgresql_server.yml'
- import_playbook: 'python.yml'
- import_playbook: 'python_venv.yml'
- import_playbook: 'qemu_guest_agent.yml'
- import_playbook: 'redis.yml'
- import_playbook: 'repo_baseos.yml'
- import_playbook: 'repo_collabora.yml'
- import_playbook: 'repo_collabora_code.yml'
- import_playbook: 'repo_debian_base.yml'
- import_playbook: 'repo_docker.yml'
- import_playbook: 'repo_elasticsearch.yml'
- import_playbook: 'repo_elasticsearch_oss.yml'
- import_playbook: 'repo_epel.yml'
- import_playbook: 'repo_gitlab_ce.yml'
- import_playbook: 'repo_gitlab_runner.yml'
- import_playbook: 'repo_grafana.yml'
- import_playbook: 'repo_graylog.yml'
- import_playbook: 'repo_icinga.yml'
- import_playbook: 'repo_influxdb.yml'
- import_playbook: 'repo_mariadb.yml'
- import_playbook: 'repo_mongodb.yml'
- import_playbook: 'repo_monitoring_plugins.yml'
- import_playbook: 'repo_mydumper.yml'
- import_playbook: 'repo_opensearch.yml'
- import_playbook: 'repo_postgresql.yml'
- import_playbook: 'repo_remi.yml'
- import_playbook: 'repo_rpmfusion.yml'
- import_playbook: 'repo_sury.yml'
- import_playbook: 'rsyslog.yml'
- import_playbook: 'selinux.yml'
- import_playbook: 'setup_basic.yml'
- import_playbook: 'setup_grav.yml'
- import_playbook: 'setup_graylog_server.yml'
- import_playbook: 'setup_icinga2_master.yml'
- import_playbook: 'setup_keycloak.yml'
- import_playbook: 'setup_librenms.yml'
- import_playbook: 'setup_nextcloud.yml'
- import_playbook: 'setup_rocketchat.yml'
- import_playbook: 'setup_wordpress.yml'
- import_playbook: 'snmp.yml'
- import_playbook: 'sshd.yml'
- import_playbook: 'system_update.yml'
- import_playbook: 'systemd_journald.yml'
- import_playbook: 'systemd_unit.yml'
- import_playbook: 'tar.yml'
- import_playbook: 'telegraf.yml'
- import_playbook: 'timezone.yml'
- import_playbook: 'tools.yml'
- import_playbook: 'unattended_upgrades.yml'
- import_playbook: 'yum_utils.yml'
