- name: 'Install at'
  collections: ['linuxfabrik.lfops']
  hosts:
    - 'lfops_at'

  roles:

    - role: 'at'
      when:
        - ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] in ['7', '8']
          or ansible_facts['distribution'] == 'Fedora'
          or ansible_facts['os_family'] == 'Debian'
          or ansible_facts['os_family'] == 'Suse'
