- name: 'Install glances'
  hosts:
    - 'lfops_glances'

  roles:

    - role: 'linuxfabrik.lfops.repo_epel'
      when:
        - 'ansible_facts["os_family"] == "RedHat" and ansible_facts["distribution_major_version"] in ["7", "8"]'

    - role: 'linuxfabrik.lfops.glances'
