logstash__java_opts: '-Djava.io.tmpdir={{ logstash__path_data }}/tmp'
logstash__log_level: 'info'
logstash__node_name: '{{ ansible_facts["nodename"] }}'
logstash__path_data: '/var/lib/logstash'
logstash__path_logs: '/var/log/logstash'
logstash__pipelines__combined_var: '{{ (
      logstash__pipelines__role_var +
      logstash__pipelines__dependent_var +
      logstash__pipelines__group_var +
      logstash__pipelines__host_var
    ) | linuxfabrik.lfops.combine_lod(unique_key="pipeline_id")
  }}'
logstash__pipelines__dependent_var: []
logstash__pipelines__group_var: []
logstash__pipelines__host_var: []
logstash__pipelines__role_var: []
logstash__raw: ''
logstash__service_enabled: true
logstash__service_state: 'started'
