php__ini_date_timezone__role_var: 'Europe/Zurich'
php__ini_default_socket_timeout__role_var: 10
php__ini_display_errors__role_var: 'Off'
php__ini_display_startup_errors__role_var: 'Off'
php__ini_error_reporting__role_var: 'E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT'
php__ini_max_execution_time__role_var: 30
php__ini_max_file_uploads__role_var: 50
php__ini_max_input_time__role_var: -1
php__ini_max_input_vars__role_var: 1000
php__ini_memory_limit__role_var: '128M'
php__ini_opcache_blacklist_filename__role_var: '/etc/php-zts.d/opcache*.blacklist'
php__ini_opcache_enable__role_var: 1
php__ini_opcache_enable_cli__role_var: 1
php__ini_opcache_huge_code_pages__role_var: 0
php__ini_opcache_interned_strings_buffer__role_var: 12
php__ini_opcache_max_accelerated_files__role_var: 7963
php__ini_opcache_memory_consumption__role_var: 128
php__ini_opcache_revalidate_freq__role_var: 60
php__ini_opcache_save_comments__role_var: 1
php__ini_opcache_validate_timestamps__role_var: 1
php__ini_post_max_size__role_var: '8M'
php__ini_session_cookie_httponly__role_var: 'Off'
php__ini_session_cookie_secure__role_var: 'Off'
php__ini_session_gc_maxlifetime__role_var: 1440
php__ini_session_sid_length__role_var: 32
php__ini_session_trans_sid_tags__role_var: 'a=href,area=href,frame=src,input=src,form=fakeentry'
php__ini_smtp__role_var: 'localhost'
php__ini_upload_max_filesize__role_var: '2M'
