# note: only use `__role_var`s in here, to allow the user to change the values

mariadb_server__cnf_bind_address__role_var: ''
mariadb_server__cnf_binlog_cache_size__role_var: '32768'
mariadb_server__cnf_binlog_expire_logs_seconds__role_var: '0'
mariadb_server__cnf_binlog_format__role_var: 'MIXED'
mariadb_server__cnf_bulk_insert_buffer_size__role_var: '8M'
mariadb_server__cnf_character_set_server__role_var: 'utf8mb4'
mariadb_server__cnf_client_ssl_ca__role_var: '{{ mariadb_server__cnf_ssl_ca__combined_var }}'
mariadb_server__cnf_client_ssl_cert__role_var: ''
mariadb_server__cnf_client_ssl_key__role_var: ''
mariadb_server__cnf_client_ssl_verify_server_cert__role_var: false
mariadb_server__cnf_collation_server__role_var: 'utf8mb4_unicode_ci'
mariadb_server__cnf_datadir__role_var: '/var/lib/mysql/'
mariadb_server__cnf_default_storage_engine__role_var: 'InnoDB'
mariadb_server__cnf_eq_range_index_dive_limit__role_var: '200'
mariadb_server__cnf_expire_logs_days__role_var: 0.000000
mariadb_server__cnf_extra_max_connections__role_var: 3
mariadb_server__cnf_extra_port__role_var: 3307
mariadb_server__cnf_general_log__role_var: 'OFF'
mariadb_server__cnf_general_log_file__role_var: '/var/log/mariadb/mariadb-general.log'
mariadb_server__cnf_innodb_adaptive_hash_index__role_var: 'OFF'
mariadb_server__cnf_innodb_adaptive_hash_index_parts__role_var: '8'
mariadb_server__cnf_innodb_autoinc_lock_mode__role_var: 1
mariadb_server__cnf_innodb_buffer_pool_chunk_size__role_var: '0' # autosized
mariadb_server__cnf_innodb_buffer_pool_size__role_var: '128M'
mariadb_server__cnf_innodb_doublewrite__role_var: 'ON'
mariadb_server__cnf_innodb_file_per_table__role_var: 'ON'
mariadb_server__cnf_innodb_flush_log_at_trx_commit__role_var: 1
mariadb_server__cnf_innodb_io_capacity__role_var: 200
mariadb_server__cnf_innodb_log_buffer_size__role_var: '16M'
mariadb_server__cnf_innodb_log_file_size__role_var: '32M'  # default: '96M'
mariadb_server__cnf_innodb_max_dirty_pages_pct__role_var: '90'
mariadb_server__cnf_innodb_max_purge_lag__role_var: '0'
mariadb_server__cnf_innodb_open_files__role_var: 0 # results in autosized
mariadb_server__cnf_innodb_print_all_deadlocks__role_var: 'OFF'
mariadb_server__cnf_innodb_purge_batch_size__role_var: '127'
mariadb_server__cnf_innodb_read_io_threads__role_var: '4'
mariadb_server__cnf_innodb_strict_mode__role_var: 'ON'
mariadb_server__cnf_innodb_sync_spin_loops__role_var: '30'
mariadb_server__cnf_innodb_write_io_threads__role_var: '4'
mariadb_server__cnf_interactive_timeout__role_var: 28800
mariadb_server__cnf_join_buffer_size__role_var: '256K'
mariadb_server__cnf_local_infile__role_var: 'ON'
mariadb_server__cnf_lock_wait_timeout__role_var: '86400'
mariadb_server__cnf_log_bin__role_var: ''
mariadb_server__cnf_log_bin_trust_function_creators__role_var: 'OFF'
mariadb_server__cnf_log_error__role_var: '/var/log/mariadb/mariadb.log'
mariadb_server__cnf_long_query_time__role_var: '10'
mariadb_server__cnf_lower_case_table_names__role_var: 0
mariadb_server__cnf_max_allowed_packet__role_var: '16M'
mariadb_server__cnf_max_connections__role_var: 64
mariadb_server__cnf_max_heap_table_size__role_var: '16M'
mariadb_server__cnf_net_read_timeout__role_var: '30'
mariadb_server__cnf_net_write_timeout__role_var: '60'
mariadb_server__cnf_performance_schema__role_var: 'ON'
mariadb_server__cnf_plugin_maturity__role_var: ''
mariadb_server__cnf_query_cache_limit__role_var: '1M'
mariadb_server__cnf_query_cache_size__role_var: 0
mariadb_server__cnf_query_cache_type__role_var: 'OFF'
mariadb_server__cnf_require_secure_transport__role_var: 'OFF' # default: 'OFF'
mariadb_server__cnf_server_id__role_var: '1'
mariadb_server__cnf_skip_name_resolve__role_var: 'ON'
mariadb_server__cnf_slow_query_log__role_var: 'OFF'
mariadb_server__cnf_slow_query_log_file__role_var: '/var/log/mariadb/mariadb-slowquery.log'
mariadb_server__cnf_sql_mode__role_var: 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
mariadb_server__cnf_ssl_ca__role_var: ''
mariadb_server__cnf_ssl_cert__role_var: ''
mariadb_server__cnf_ssl_key__role_var: ''
mariadb_server__cnf_table_definition_cache__role_var: 400
mariadb_server__cnf_table_open_cache__role_var: '2000'
mariadb_server__cnf_tls_version__role_var: 'TLSv1.2,TLSv1.3'
mariadb_server__cnf_tmp_table_size__role_var: '16M'
mariadb_server__cnf_tmpdir__role_var: ''
mariadb_server__cnf_wait_timeout__role_var: 28800

# DARE using the File Key Management plugin
mariadb_server__cnf_encrypt_binlog__role_var: 'ON'
mariadb_server__cnf_encrypt_tmp_files__role_var: 'ON'
mariadb_server__cnf_file_key_management_encryption_algorithm__role_var: 'AES_CTR'
mariadb_server__cnf_file_key_management_filename__role_var: '/etc/my.cnf.d/keyfile'
mariadb_server__cnf_innodb_default_encryption_key_id__role_var: 1
mariadb_server__cnf_innodb_encrypt_log__role_var: 'ON'
mariadb_server__cnf_innodb_encrypt_tables__role_var: 'ON'
mariadb_server__cnf_innodb_encrypt_temporary_tables__role_var: 'ON'
mariadb_server__cnf_innodb_encryption_rotate_key_age__role_var: 1
mariadb_server__cnf_innodb_encryption_threads__role_var: 4
mariadb_server__cnf_plugin_load_add__role_var: 'file_key_management'

# ===

mariadb_server__logrotate_path: '/etc/logrotate.d/mariadb' # internal variable, not intended for the user
